name: 'dm2_bike_weather'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dm2_bike_weather:
    marts:
      +materialized: table
      +schema: marts